
export interface Question {
  id: number;
  text: string;
  subscale: 'social_relatedness' | 'circumscribed_interests' | 'language' | 'sensory_motor';
  isReverseScored: boolean;
}

export const questions: Question[] = [
  { id: 1, text: "I am a sympathetic person.", subscale: 'social_relatedness', isReverseScored: true },
  { id: 2, text: "I often use words and phrases from movies and television in conversations.", subscale: 'language', isReverseScored: false },
  { id: 3, text: "I am often surprised when others tell me I have been rude.", subscale: 'social_relatedness', isReverseScored: false },
  { id: 4, text: "Sometimes I talk to loudly or too softly and I am not aware of it.", subscale: 'sensory_motor', isReverseScored: false },
  { id: 5, text: "I often don't know how to act in social situations.", subscale: 'social_relatedness', isReverseScored: false },
  { id: 6, text: "I can \"put myself in other people's shoes.\"", subscale: 'social_relatedness', isReverseScored: true },
  { id: 7, text: "I have a hard time figuring out what some phrases mean, like \"you are the apple of my eye\".", subscale: 'language', isReverseScored: false },
  { id: 8, text: "I only like to talk to people who share my special interests.", subscale: 'social_relatedness', isReverseScored: false },
  { id: 9, text: "I focus on details rather than the overall idea.", subscale: 'circumscribed_interests', isReverseScored: false },
  { id: 10, text: "I always notice how food feels in my mouth. This is more important to me than how it tastes.", subscale: 'sensory_motor', isReverseScored: false },
  { id: 11, text: "I miss my best friends or family when we are apart for a long time.", subscale: 'social_relatedness', isReverseScored: true },
  { id: 12, text: "Sometimes I offend others by saying what I am thinking, even if I don't mean to.", subscale: 'social_relatedness', isReverseScored: false },
  { id: 13, text: "I only like to think and talk about a few things that interest me.", subscale: 'circumscribed_interests', isReverseScored: false },
  { id: 14, text: "I'd rather go out to eat in a restaurant by myself than with someone I know.", subscale: 'social_relatedness', isReverseScored: false },
  { id: 15, text: "I cannot imagine what it would be like to be someone else.", subscale: 'language', isReverseScored: false },
  { id: 16, text: "I have been told that I am clumsy or uncoordinated.", subscale: 'sensory_motor', isReverseScored: false },
  { id: 17, text: "Others consider me odd or different.", subscale: 'social_relatedness', isReverseScored: false },
  { id: 18, text: "I understand when friends need to be comforted.", subscale: 'social_relatedness', isReverseScored: true },
  { id: 19, text: "I am very sensitive to the way my clothes feel when I touch them. How they feel is more important to me than how they look.", subscale: 'sensory_motor', isReverseScored: false },
  { id: 20, text: "I like to copy the way certain people speak and act. It helps me appear more normal.", subscale: 'social_relatedness', isReverseScored: false },
  { id: 21, text: "It can be very intimidating for me to talk to more than one person at a time.", subscale: 'social_relatedness', isReverseScored: false },
  { id: 22, text: "I have to \"act normal\" to please other people and make them like me.", subscale: 'social_relatedness', isReverseScored: false },
  { id: 23, text: "Meeting new people is usually easy for me.", subscale: 'social_relatedness', isReverseScored: true },
  { id: 24, text: "I get highly confused when someone interrupts me when I am talking about something I am very interested in.", subscale: 'circumscribed_interests', isReverseScored: false },
  { id: 25, text: "It is difficult for me to understand how other people are feeling when we are talking.", subscale: 'social_relatedness', isReverseScored: false },
  { id: 26, text: "I like having a conversation with several people, for instance around a dinner table, at school or at work.", subscale: 'social_relatedness', isReverseScored: true },
  { id: 27, text: "I take things too literally, so often I miss what people are trying to say.", subscale: 'language', isReverseScored: false },
  { id: 28, text: "It is very difficult for me to understand when someone is embarrassed or jealous.", subscale: 'social_relatedness', isReverseScored: false },
  { id: 29, text: "Some ordinary textures that do not bother others feel very offensive when they touch my skin.", subscale: 'sensory_motor', isReverseScored: false },
  { id: 30, text: "I get extremely upset when the way I like to do things is suddenly changed.", subscale: 'circumscribed_interests', isReverseScored: false },
  { id: 31, text: "I have never wanted or needed to have what other people call an \"intimate relationship\".", subscale: 'social_relatedness', isReverseScored: false },
  { id: 32, text: "It is difficult for me to start and stop a conversation. I need to keep going until I am finished.", subscale: 'circumscribed_interests', isReverseScored: false },
  { id: 33, text: "I speak with a normal rhythm.", subscale: 'sensory_motor', isReverseScored: true },
  { id: 34, text: "The same sound, color or texture can suddenly change from very sensitive to very dull.", subscale: 'sensory_motor', isReverseScored: false },
  { id: 35, text: "The phrase \"I've got you under my skin\" makes me very uncomfortable.", subscale: 'language', isReverseScored: false },
  { id: 36, text: "Sometimes the sound of a word or high-pitched noise can be painful to my ears.", subscale: 'sensory_motor', isReverseScored: false },
  { id: 37, text: "I am an understanding type of person.", subscale: 'social_relatedness', isReverseScored: true },
  { id: 38, text: "I do not connect with characters in movies and cannot feel what they feel.", subscale: 'social_relatedness', isReverseScored: false },
  { id: 39, text: "I cannot tell what someone is flirting with me.", subscale: 'social_relatedness', isReverseScored: false },
  { id: 40, text: "I can see in my mind in exact detail things that I am interested in.", subscale: 'circumscribed_interests', isReverseScored: false },
  { id: 41, text: "I keep lists of things that interest me, even when they have no practical use (for example sports statistics, train schedules, calendar dates, historical facts and dates).", subscale: 'circumscribed_interests', isReverseScored: false },
  { id: 42, text: "When I feel overwhelmed by my senses, I have to isolate myself to shut them down.", subscale: 'sensory_motor', isReverseScored: false },
  { id: 43, text: "I like to talk things over with my friends.", subscale: 'social_relatedness', isReverseScored: true },
  { id: 44, text: "I cannot tell if someone is interested or bored with what I am saying.", subscale: 'social_relatedness', isReverseScored: false },
  { id: 45, text: "It can be very hard to read someone's face, hand and body movements when they are talking.", subscale: 'social_relatedness', isReverseScored: false },
  { id: 46, text: "The same thing (like clothes or temperature) can feel very different to me at different times.", subscale: 'sensory_motor', isReverseScored: false },
  { id: 47, text: "I feel very comfortable with dating or being in social situations with others.", subscale: 'social_relatedness', isReverseScored: true },
  { id: 48, text: "I try to be as helpful as I can when other people tell me their personal problems.", subscale: 'social_relatedness', isReverseScored: true },
  { id: 49, text: "I have been told that I have an unusual voice (for example flat, monotone, childish, or high-pitched).", subscale: 'sensory_motor', isReverseScored: false },
  { id: 50, text: "Sometimes a thought or a subject gets stuck in my mind and I have to talk about it even if no one is interested.", subscale: 'circumscribed_interests', isReverseScored: false },
  { id: 51, text: "I do certain things with my hands over and over again (like flapping, twirling sticks or strings, waving things by my eyes).", subscale: 'sensory_motor', isReverseScored: false },
  { id: 52, text: "I have never been interested in what most of the people I know consider interesting.", subscale: 'circumscribed_interests', isReverseScored: false },
  { id: 53, text: "I am considered a compassionate type of person.", subscale: 'social_relatedness', isReverseScored: true },
  { id: 54, text: "I get along with other people by following a set of specific rules that help me look normal.", subscale: 'social_relatedness', isReverseScored: false },
  { id: 55, text: "It is very difficult for me to work and function in groups.", subscale: 'social_relatedness', isReverseScored: false },
  { id: 56, text: "When I am talking to someone, it is hard to change the subject. If the other person does so, I can get very upset and confused.", subscale: 'circumscribed_interests', isReverseScored: false },
  { id: 57, text: "Sometimes I have to cover my ears to block out painful noises (like vacuum cleaners or people talking too much or too loudly).", subscale: 'sensory_motor', isReverseScored: false },
  { id: 58, text: "I can chat and make small talk with people.", subscale: 'language', isReverseScored: true },
  { id: 59, text: "Sometimes things that should feel painful are not (for instance when I hurt myself or burn my hand on a stove)", subscale: 'sensory_motor', isReverseScored: false },
  { id: 60, text: "When talking to someone, I have a hard time telling when it is my turn to talk or listen.", subscale: 'social_relatedness', isReverseScored: false },
  { id: 61, text: "I am considered a loner by those who know me best.", subscale: 'social_relatedness', isReverseScored: false },
  { id: 62, text: "I usually speak in a normal tone.", subscale: 'sensory_motor', isReverseScored: true },
  { id: 63, text: "I like things to be exactly the same day after day and even small changes in my routines upset me.", subscale: 'circumscribed_interests', isReverseScored: false },
  { id: 64, text: "How to make friends and socialize is a mystery to me.", subscale: 'social_relatedness', isReverseScored: false },
  { id: 65, text: "It calms me to spin around or to rock in a chair when I am feeling stressed.", subscale: 'sensory_motor', isReverseScored: false },
  { id: 66, text: "The phrase, \"He wears his heart on his sleeve.\" does not make sense to me.", subscale: 'language', isReverseScored: false },
  { id: 67, text: "If I am in a place where there are many smells, textures to feel, noises or bright lights, I feel anxious or frightened.", subscale: 'sensory_motor', isReverseScored: false },
  { id: 68, text: "I can tell when someone says one thing but means something else.", subscale: 'social_relatedness', isReverseScored: true },
  { id: 69, text: "I like to be by myself as much as I can.", subscale: 'social_relatedness', isReverseScored: false },
  { id: 70, text: "I keep my thoughts stacked in my memory like they are on filing cards, and I pick out the ones I need by looking through the stack and finding the right one (or another unique way).", subscale: 'circumscribed_interests', isReverseScored: false },
  { id: 71, text: "The same sound sometimes seems very loud or very soft, even though I know it has not changed.", subscale: 'sensory_motor', isReverseScored: false },
  { id: 72, text: "I enjoy spending time eating and talking with my family and friends.", subscale: 'social_relatedness', isReverseScored: true },
  { id: 73, text: "I can't tolerate things I dislike (like smells, textures, sounds or colors).", subscale: 'sensory_motor', isReverseScored: false },
  { id: 74, text: "I don't like to be hugged or held.", subscale: 'sensory_motor', isReverseScored: false },
  { id: 75, text: "When I go somewhere, I have to follow a familiar route or I can get very confused and upset.", subscale: 'circumscribed_interests', isReverseScored: false },
  { id: 76, text: "It is difficult to figure out what other people expect of me.", subscale: 'social_relatedness', isReverseScored: false },
  { id: 77, text: "I like to have close friends.", subscale: 'social_relatedness', isReverseScored: true },
  { id: 78, text: "People tell me that I give too much detail.", subscale: 'circumscribed_interests', isReverseScored: false },
  { id: 79, text: "I am often told that I ask embarrasing questions.", subscale: 'social_relatedness', isReverseScored: false },
  { id: 80, text: "I tend to point out other people's mistakes.", subscale: 'social_relatedness', isReverseScored: false },
];
